config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :phone_number, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5], allow_nil: false }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to restaurants_path(@restaurant)
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    Restaurant.find(params[:id]).update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    Restaurant.find(params[:id]).destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
  end

  def create
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <p>Name:</p> <%= f.text_field :name %>
  <p>Address :</p> <%= f.text_field :address %>
  <p>Phone Number :</p> <%= f.text_field :phone_number %>
  <p>Category :</p> <%= f.text_field :category %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1> List of all restaurants </h1>
<article>

  <% @restaurants.each do |restaurant| %>
    <ul>
      <li><strong>Name</strong> : <%= restaurant.name %></li>
      <li><strong>Address :</strong> <%= restaurant.address %></li>
      <li><strong>Phone Number :</strong> <%= restaurant.phone_number %></li>
      <li><strong>Category :</strong> <%= restaurant.category %></li>
    </ul>

    <p><%= link_to 'show', restaurant_path(restaurant) %> |
    <%= link_to 'edit', edit_restaurant_path(restaurant) %> |
    <%= link_to 'delete', restaurant_path(restaurant), method: 'delete' %>
    </p>

  <% end %>

</article>

<%= link_to 'add new', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Add a New Restaurant</h1>
<%= render 'form' %>

app/views/restaurants/show.html.erb
<p>under construction...</p>
<%= link_to 'back', restaurants_path %>